### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by ikhthiandor** [stayradiated/rango#2]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with rango. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable rango on @Sourcegraph by going to https://sourcegraph.com/github.com/stayradiated/rango and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by stayradiated** [comment]
Done.
